name: Update Playlist

on:
  schedule:
    - cron: '0 0 * * 0' # Runs once a week (at midnight on Sunday)
  push:
    branches:
      - main

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install google-api-python-client

      - name: Fetch and update playlist
        run: python scripts/update_playlist.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add static/playlist_data.json
          git commit -m 'Update playlist data'
          git push
